name: Build AmneziaWG for OpenWrt

on:
  push:
    tags:
      - 'v*.*.*'  # запускать при создании тега вида v1.0.0

jobs:
  build:
    name: Build AWG for ${{ matrix.build_env.target }}/ ${{ matrix.build_env.subtarget }} (OpenWrt ${{ matrix.build_env.tag }}, arch ${{ matrix.build_env.pkgarch }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_env:
          - tag: "19.07.3"
            pkgarch: mips_24kc
            target: ramips
            subtarget: mt7620
            vermagic: "4.14.180"  # версия ядра вашего роутера
    steps:
      - uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v${{ matrix.build_env.tag }}
          fetch-depth: 0

      - name: Setup feed for AmneziaWG
        run: |
          echo "src-git awg https://github.com/Slava-Shchipunov/awg-openwrt.git" >> feeds.conf.default
          ./scripts/feeds update awg
          ./scripts/feeds install awg
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build
        run: |
          wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/config.buildinfo -O .config
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-amneziawg=y" >> .config
          ./scripts/feeds update -a
          ./scripts/feeds install awg amneziawg-tools luci-app-amneziawg
          make defconfig

      - name: Build Kernel Module & Packages
        run: |
          make -j$(nproc) V=s

      - name: Collect artifacts
        run: |
          mkdir -p artifacts
          cp bin/packages/${{ matrix.build_env.pkgarch }}/awg/*.ipk artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.ipk
