name: Build AmneziaWG for OpenWrt

on:
  push:
    tags:
      - 'v*.*.*'  # запускать при создании тега вида v1.0.0

jobs:
  build:
    name: Build AWG for ${{ matrix.build_env.target }}/ ${{ matrix.build_env.subtarget }} (OpenWrt ${{ matrix.build_env.tag }}, arch ${{ matrix.build_env.pkgarch }})
    runs-on: ubuntu-18.04  # Используем Ubuntu 18.04 для совместимости с OpenWrt 19.07

    strategy:
      matrix:
        build_env:
          - tag: "19.07.3"
            pkgarch: mips_24kc
            target: ramips
            subtarget: mt7620
            vermagic: "4.14.180"  # версия ядра вашего роутера

    steps:
      - uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v${{ matrix.build_env.tag }}
          fetch-depth: 0

      - name: Установка зависимостей
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python2 \
            gcc-7 \
            g++-7 \
            libncurses5-dev \
            zlib1g-dev \
            libssl-dev \
            git

      - name: Настройка feed для AmneziaWG
        run: |
          echo "src-git awg https://github.com/Slava-Shchipunov/awg-openwrt.git" >> feeds.conf.default
          ./scripts/feeds update awg
          ./scripts/feeds install awg
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Конфигурация сборки
        run: |
          wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/config.buildinfo -O .config
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-amneziawg=y" >> .config
          ./scripts/feeds update -a
          ./scripts/feeds install awg amneziawg-tools luci-app-amneziawg
          make defconfig

      - name: Сборка Kernel Module & Пакетов
        run: |
          make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
        run: |
          FORCE=1 make -j$(nproc) V=s

      - name: Сборка с принудительным обходом проверок
::contentReference[oaicite:4]{index=4}
 
